// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/proto/uuid_generator.proto

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	rpc/proto/uuid_generator.proto

It has these top-level messages:
	SnowflakeKey
	SnowflakeVal
	SnowflakeNullReq
	SnowflakeUUID
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SnowflakeKey struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *SnowflakeKey) Reset()                    { *m = SnowflakeKey{} }
func (m *SnowflakeKey) String() string            { return proto.CompactTextString(m) }
func (*SnowflakeKey) ProtoMessage()               {}
func (*SnowflakeKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SnowflakeKey) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SnowflakeVal struct {
	Value int64 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (m *SnowflakeVal) Reset()                    { *m = SnowflakeVal{} }
func (m *SnowflakeVal) String() string            { return proto.CompactTextString(m) }
func (*SnowflakeVal) ProtoMessage()               {}
func (*SnowflakeVal) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SnowflakeVal) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type SnowflakeNullReq struct {
}

func (m *SnowflakeNullReq) Reset()                    { *m = SnowflakeNullReq{} }
func (m *SnowflakeNullReq) String() string            { return proto.CompactTextString(m) }
func (*SnowflakeNullReq) ProtoMessage()               {}
func (*SnowflakeNullReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type SnowflakeUUID struct {
	Uuid uint64 `protobuf:"varint,1,opt,name=uuid" json:"uuid,omitempty"`
}

func (m *SnowflakeUUID) Reset()                    { *m = SnowflakeUUID{} }
func (m *SnowflakeUUID) String() string            { return proto.CompactTextString(m) }
func (*SnowflakeUUID) ProtoMessage()               {}
func (*SnowflakeUUID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SnowflakeUUID) GetUuid() uint64 {
	if m != nil {
		return m.Uuid
	}
	return 0
}

func init() {
	proto.RegisterType((*SnowflakeKey)(nil), "protobuf.SnowflakeKey")
	proto.RegisterType((*SnowflakeVal)(nil), "protobuf.SnowflakeVal")
	proto.RegisterType((*SnowflakeNullReq)(nil), "protobuf.SnowflakeNullReq")
	proto.RegisterType((*SnowflakeUUID)(nil), "protobuf.SnowflakeUUID")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Generator service

type GeneratorClient interface {
	Next(ctx context.Context, in *SnowflakeKey, opts ...grpc.CallOption) (*SnowflakeVal, error)
	GetUUID(ctx context.Context, in *SnowflakeNullReq, opts ...grpc.CallOption) (*SnowflakeUUID, error)
}

type generatorClient struct {
	cc *grpc.ClientConn
}

func NewGeneratorClient(cc *grpc.ClientConn) GeneratorClient {
	return &generatorClient{cc}
}

func (c *generatorClient) Next(ctx context.Context, in *SnowflakeKey, opts ...grpc.CallOption) (*SnowflakeVal, error) {
	out := new(SnowflakeVal)
	err := grpc.Invoke(ctx, "/protobuf.Generator/Next", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *generatorClient) GetUUID(ctx context.Context, in *SnowflakeNullReq, opts ...grpc.CallOption) (*SnowflakeUUID, error) {
	out := new(SnowflakeUUID)
	err := grpc.Invoke(ctx, "/protobuf.Generator/GetUUID", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Generator service

type GeneratorServer interface {
	Next(context.Context, *SnowflakeKey) (*SnowflakeVal, error)
	GetUUID(context.Context, *SnowflakeNullReq) (*SnowflakeUUID, error)
}

func RegisterGeneratorServer(s *grpc.Server, srv GeneratorServer) {
	s.RegisterService(&_Generator_serviceDesc, srv)
}

func _Generator_Next_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnowflakeKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneratorServer).Next(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Generator/Next",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneratorServer).Next(ctx, req.(*SnowflakeKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Generator_GetUUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnowflakeNullReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneratorServer).GetUUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Generator/GetUUID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneratorServer).GetUUID(ctx, req.(*SnowflakeNullReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Generator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Generator",
	HandlerType: (*GeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Next",
			Handler:    _Generator_Next_Handler,
		},
		{
			MethodName: "GetUUID",
			Handler:    _Generator_GetUUID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/proto/uuid_generator.proto",
}

func init() { proto.RegisterFile("rpc/proto/uuid_generator.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x29, 0x2a, 0x48, 0xd6,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0xcf, 0x4c, 0x89, 0x4f, 0x4f, 0xcd, 0x4b, 0x2d, 0x4a, 0x2c,
	0xc9, 0x2f, 0xd2, 0x03, 0x0b, 0x09, 0x71, 0x80, 0xa9, 0xa4, 0xd2, 0x34, 0x25, 0x25, 0x2e, 0x9e,
	0xe0, 0xbc, 0xfc, 0xf2, 0xb4, 0x9c, 0xc4, 0xec, 0x54, 0xef, 0xd4, 0x4a, 0x21, 0x21, 0x2e, 0x96,
	0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b, 0x49, 0x05, 0x49,
	0x4d, 0x58, 0x62, 0x8e, 0x90, 0x08, 0x17, 0x6b, 0x59, 0x62, 0x4e, 0x29, 0x44, 0x11, 0x73, 0x10,
	0x84, 0xa3, 0x24, 0xc4, 0x25, 0x00, 0x57, 0xe5, 0x57, 0x9a, 0x93, 0x13, 0x94, 0x5a, 0xa8, 0xa4,
	0xcc, 0xc5, 0x0b, 0x17, 0x0b, 0x0d, 0xf5, 0x74, 0x01, 0x19, 0x5f, 0x5a, 0x9a, 0x99, 0x02, 0xd6,
	0xc9, 0x12, 0x04, 0x66, 0x1b, 0xb5, 0x33, 0x72, 0x71, 0xba, 0xc3, 0x1c, 0x28, 0x64, 0xc1, 0xc5,
	0xe2, 0x97, 0x5a, 0x51, 0x22, 0x24, 0xa6, 0x07, 0x73, 0xa3, 0x1e, 0xb2, 0x03, 0xa5, 0xb0, 0x89,
	0x87, 0x25, 0xe6, 0x28, 0x31, 0x08, 0x39, 0x70, 0xb1, 0xbb, 0xa7, 0x96, 0x80, 0xad, 0x91, 0xc2,
	0xa2, 0x08, 0xea, 0x26, 0x29, 0x71, 0x2c, 0x72, 0x20, 0x4d, 0x4a, 0x0c, 0x49, 0x6c, 0x60, 0x19,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x3a, 0xe5, 0x7b, 0x3d, 0x01, 0x00, 0x00,
}
